import type { Metadata } from "next";
import { Press_Start_2P as FontPressStart } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import Provider from "@/components/provider";
import { Toaster } from "@/components/ui/sonner";

const fontPress = FontPressStart({
  weight: "400",
  subsets: ["cyrillic"],
  variable: "--font-press",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-press antialiased",
          fontPress.variable
        )}
      >
        <Provider>{children}</Provider>
        <Toaster richColors />
      </body>
    </html>
  );
}
